/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 31 13:13:07 GMT 2026
 */

package assignment8_exercises.fail2ban;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment8_exercises.fail2ban.IP;
import assignment8_exercises.fail2ban.Server;
import assignment8_exercises.fail2ban.StrictlySortedSinglyLinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Server_Failed_ESTest extends Server_Failed_ESTest_scaffolding {

  // Contract violation: Undeclared exception check
  // Contract violation: NullPointerException

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Server server0 = new Server();
      server0.bans = null;
      // Throws undeclared exception: null
      // Undeclared exception!
      server0.update();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Server server0 = new Server();
      server0.bans = null;
      // Throws NullPointerException: null
      // Undeclared exception!
      server0.update();
  }

  // Contract violation: Undeclared exception check
  // Contract violation: NullPointerException

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Server server0 = new Server();
      server0.exceptions = null;
      Integer integer0 = new Integer(1);
      IP iP0 = new IP(integer0, (Integer) null, (Integer) null, integer0);
      // Throws undeclared exception: null
      // Undeclared exception!
      server0.addBan(iP0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Server server0 = new Server();
      server0.exceptions = null;
      Integer integer0 = new Integer(1);
      IP iP0 = new IP(integer0, (Integer) null, (Integer) null, integer0);
      // Throws NullPointerException: null
      // Undeclared exception!
      server0.addBan(iP0);
  }

  // Contract violation: Undeclared exception (JCrasher style)

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer(2);
      StrictlySortedSinglyLinkedList strictlySortedSinglyLinkedList0 = new StrictlySortedSinglyLinkedList();
      strictlySortedSinglyLinkedList0.header = null;
      server0.bans = strictlySortedSinglyLinkedList0;
      IP iP0 = new IP(integer0, integer0, integer0, integer0);
      // Throws undeclared exception (JCrasher heuristic): null
      // Undeclared exception!
      server0.addBan(iP0);
  }

  // Contract violation: Undeclared exception check
  // Contract violation: NullPointerException

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer(1);
      server0.bans = null;
      Integer integer1 = new Integer(1);
      IP iP0 = new IP(integer0, integer0, integer0, integer1);
      // Throws undeclared exception: null
      // Undeclared exception!
      server0.removeBan(iP0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer(1);
      server0.bans = null;
      Integer integer1 = new Integer(1);
      IP iP0 = new IP(integer0, integer0, integer0, integer1);
      // Throws NullPointerException: null
      // Undeclared exception!
      server0.removeBan(iP0);
  }
}
