/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 31 13:13:07 GMT 2026
 */

package assignment8_exercises.fail2ban;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment8_exercises.fail2ban.IP;
import assignment8_exercises.fail2ban.IPBan;
import assignment8_exercises.fail2ban.ITime;
import assignment8_exercises.fail2ban.RealTime;
import assignment8_exercises.fail2ban.Server;
import assignment8_exercises.fail2ban.SinglyLinkedList;
import assignment8_exercises.fail2ban.StrictlySortedSinglyLinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Server_ESTest extends Server_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Server server0 = new Server();
      StrictlySortedSinglyLinkedList strictlySortedSinglyLinkedList0 = server0.bans;
      strictlySortedSinglyLinkedList0.size = (-2135);
      server0.update();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Server server0 = new Server();
      server0.bans = null;
      // Undeclared exception!
      try { 
        server0.update();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment8_exercises.fail2ban.Server", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer(1);
      server0.bans = null;
      IP iP0 = new IP(integer0, integer0, integer0, integer0);
      // Undeclared exception!
      try { 
        server0.removeBan(iP0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment8_exercises.fail2ban.Server", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Server server0 = new Server();
      server0.exceptions = null;
      Integer integer0 = new Integer(1);
      IP iP0 = new IP(integer0, (Integer) null, (Integer) null, integer0);
      // Undeclared exception!
      try { 
        server0.addBan(iP0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("assignment8_exercises.fail2ban.Server", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Server server0 = new Server();
      server0.update();
      System.setCurrentTimeMillis(0L);
      Integer integer0 = new Integer(1);
      IP iP0 = new IP(integer0, integer0, integer0, integer0);
      boolean boolean0 = server0.addBan(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.repOK();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.addBan(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.repOK();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Server server0 = new Server();
      StrictlySortedSinglyLinkedList strictlySortedSinglyLinkedList0 = new StrictlySortedSinglyLinkedList();
      server0.bans = strictlySortedSinglyLinkedList0;
      strictlySortedSinglyLinkedList0.size = 129;
      boolean boolean0 = server0.repOK();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Server server0 = new Server();
      SinglyLinkedList singlyLinkedList0 = server0.exceptions;
      singlyLinkedList0.size = (-1);
      boolean boolean0 = server0.repOK();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Server server0 = new Server();
      server0.bans = null;
      boolean boolean0 = server0.repOK();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Server server0 = new Server();
      server0.exceptions = null;
      boolean boolean0 = server0.repOK();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Server server0 = new Server();
      StrictlySortedSinglyLinkedList strictlySortedSinglyLinkedList0 = new StrictlySortedSinglyLinkedList();
      server0.bans = strictlySortedSinglyLinkedList0;
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      Long long0 = new Long(34L);
      IPBan iPBan0 = new IPBan(iP0, long0);
      strictlySortedSinglyLinkedList0.add(iPBan0);
      server0.update();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      server0.addBan(iP0);
      server0.update();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Server server0 = new Server();
      server0.update();
      boolean boolean0 = server0.repOK();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.addBan(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.removeBan(iP0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Server server0 = new Server();
      boolean boolean0 = server0.removeBan((IP) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.removeBan(iP0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer((-1806));
      IP iP0 = new IP(integer0, integer0, (Integer) null, integer0);
      boolean boolean0 = server0.addException(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.addBan(iP0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.addBan(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.addBan(iP0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Server server0 = new Server();
      boolean boolean0 = server0.addBan((IP) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Server server0 = new Server();
      boolean boolean0 = server0.removeException((IP) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.removeException(iP0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer(0);
      IP iP0 = new IP(integer0, integer0, integer0, integer0);
      boolean boolean0 = server0.addException(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.addException(iP0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Server server0 = new Server();
      boolean boolean0 = server0.addException((IP) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.addException(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.removeException(iP0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Server server0 = new Server();
      Integer integer0 = new Integer((-1806));
      IP iP0 = new IP(integer0, integer0, (Integer) null, integer0);
      boolean boolean0 = server0.addBan(iP0);
      assertTrue(boolean0);
      
      boolean boolean1 = server0.connect(iP0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Server server0 = new Server();
      boolean boolean0 = server0.connect((IP) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Server server0 = new Server();
      IP iP0 = new IP((Integer) null, (Integer) null, (Integer) null, (Integer) null);
      boolean boolean0 = server0.connect(iP0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Server server0 = new Server();
      RealTime realTime0 = new RealTime();
      server0.setTime(realTime0);
      assertEquals(1392409281320L, realTime0.getCurrentTime());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Server server0 = new Server();
      server0.setTime((ITime) null);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Server server0 = new Server();
      String string0 = server0.toString();
      assertEquals("Server [lastUpdate=null, exceptions=(), bans={}]", string0);
  }
}
