/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 31 12:08:35 GMT 2026
 */

package assignment8_exercises.fileContents;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import assignment8_exercises.fileContents.fileExample;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class fileExample_Failed_ESTest extends fileExample_Failed_ESTest_scaffolding {

  // Contract violation: Undeclared exception check
  // Contract violation: Undeclared exception (JCrasher style)

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      fileExample fileExample0 = new fileExample();
      // Throws undeclared exception: No line found
      fileExample0.checkContent();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      fileExample fileExample0 = new fileExample();
      // Throws undeclared exception (JCrasher heuristic): No line found
      fileExample0.checkContent();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      fileExample fileExample0 = new fileExample();
      // Throws undeclared exception: null
      fileExample0.checkContent();
  }
}
